overrides:
  - files:
      - '*.js'
    extends:
      - pegasus

  - files:
      - '**/*.ts'
    parser: '@typescript-eslint/parser'
    plugins:
      - '@typescript-eslint'
    extends:
      - eslint:recommended
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - pegasus

  - files:
      - 'scripts/**/*.js'
    rules:
      import/no-extraneous-dependencies: off
      no-console: off

env:
  jest: true
  node: true
